[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ved Yadav", email = "vedyadav19057@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "langchain>=1.3.16",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.0",
    "openai>=3.3.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "rapidfuzz>=3.14.5",
    "uvicorn[standard]>=0.52.4",
]

